In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.pipeline import Pipeline

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    roc_curve
)

import warnings
warnings.filterwarnings("ignore")

print("All required libraries imported successfully.")

All required libraries imported successfully.

In [ ]:
# Load the heart disease dataset

file_path = "C:\\Users\\User\\Downloads\\heart+disease\\heart_disease_combined_raw(3).csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully.")
print("Dataset shape:", df.shape)

Dataset loaded successfully.
Dataset shape: (900, 77)

In [4]:
# Create a binary target variable

df_model = df.copy()

df_model["target"] = (df_model["num"] > 0).astype(int)

print("Binary target variable created.")

print("\nTarget values:")
print(sorted(df_model["target"].unique()))

Binary target variable created.

Target values:
[np.int64(0), np.int64(1)]

In [5]:
# Select clinical features

selected_features = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal"
]

X = df_model[selected_features].copy()

y = df_model["target"].copy()

print("Number of selected features:", len(selected_features))

print("\nSelected features:")
for feature in selected_features:
    print("-", feature)

Number of selected features: 13

Selected features:
- age
- sex
- cp
- trestbps
- chol
- fbs
- restecg
- thalach
- exang
- oldpeak
- slope
- ca
- thal

In [6]:
# Handle missing values using median imputation

for column in X.columns:
    if X[column].isnull().sum() > 0:
        X[column] = X[column].fillna(X[column].median())

print("Missing-value treatment completed.")

print("\nTotal remaining missing values:", X.isnull().sum().sum())

Missing-value treatment completed.

Total remaining missing values: 0

In [7]:
# Display the feature matrix and target

print("Feature matrix X:")
display(X.head())

print("\nTarget variable y:")
display(y.head())

Feature matrix X:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3

Target variable y:

0    0
1    1
2    1
3    0
4    0
Name: target, dtype: int64

In [8]:
# Display the feature matrix and target

print("Feature matrix X:")
display(X.head())

print("\nTarget variable y:")
display(y.head())

Feature matrix X:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3

Target variable y:

0    0
1    1
2    1
3    0
4    0
Name: target, dtype: int64

In [9]:
# Split dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Train-Test Split")
print("================")

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

Train-Test Split
================
X_train shape: (720, 13)
X_test shape : (180, 13)
y_train shape: (720,)
y_test shape : (180,)

In [10]:
# Split dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Train-Test Split")
print("================")

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

Train-Test Split
================
X_train shape: (720, 13)
X_test shape : (180, 13)
y_train shape: (720,)
y_test shape : (180,)

In [11]:
# Create Logistic Regression pipeline

logistic_model = Pipeline([
    ("scaler", StandardScaler()),
    ("logistic_regression", LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

print("Logistic Regression pipeline created successfully.")

Logistic Regression pipeline created successfully.

In [14]:
# Create Logistic Regression pipeline

logistic_model = Pipeline([
    ("scaler", StandardScaler()),
    ("logistic_regression", LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

print("Logistic Regression pipeline created successfully.")

Logistic Regression pipeline created successfully.

In [16]:
# Generate predictions on the test set
# Train the Logistic Regression model

logistic_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")
y_pred = logistic_model.predict(X_test)

# Generate probability predictions
y_prob = logistic_model.predict_proba(X_test)[:, 1]

print("Predictions generated successfully.")

print("\nFirst 10 predicted classes:")
print(y_pred[:10])

print("\nFirst 10 predicted probabilities:")
print(np.round(y_prob[:10], 4))

Logistic Regression model trained successfully.
Predictions generated successfully.

First 10 predicted classes:
[0 0 1 1 0 1 0 1 1 1]

First 10 predicted probabilities:
[0.4458 0.0884 0.7089 0.9333 0.21   0.8741 0.2427 0.5761 0.6945 0.8993]

In [17]:
# Calculate accuracy

accuracy = accuracy_score(y_test, y_pred)

print("Logistic Regression Accuracy:")
print(f"{accuracy:.4f}")

print(f"\nAccuracy Percentage: {accuracy * 100:.2f}%")

Logistic Regression Accuracy:
0.8000

Accuracy Percentage: 80.00%

In [18]:
# Calculate classification metrics

precision = precision_score(
    y_test,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0
)

print("Logistic Regression Metrics")
print("===========================")

print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

Logistic Regression Metrics
===========================
Precision : 0.8058
Recall    : 0.8384
F1 Score  : 0.8218

In [19]:
# Calculate ROC-AUC

roc_auc = roc_auc_score(
    y_test,
    y_prob
)

print("ROC-AUC Score:")
print(f"{roc_auc:.4f}")

ROC-AUC Score:
0.8677

In [20]:
# Create a performance summary table

logistic_results = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],
    
    "Score": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ]
})

display(logistic_results.round(4))

      Metric   Score
0   Accuracy  0.8000
1  Precision  0.8058
2     Recall  0.8384
3   F1 Score  0.8218
4    ROC-AUC  0.8677